[workspace]
members = ["challenge/20*/*", "lib/*"]

[workspace.package]
name = "advent-of-code-rs"
version = "0.1.0"
edition = "2021"
authors = ["Stefan Lendl"]

[workspace.dependencies]
rstest = "*"
regex = "1"
