[package]
name = "c21-02"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
read_input = { path = "../../../lib/read_input" }
regex.workspace = true

[dev-dependencies]
rstest.workspace = true
